"""
fleet_sweep_legacy.py
======================
StampFly 旧世代ログ（logs/*.csv, analysis/datasets/*, firmware/vehicle_old/logs/）
の schema survey。CW/CCW duty 非対称抽出を試みたが、対象ファイル群には
モータ個別 duty/PWM 列が一列も存在しないことを確認した記録用スクリプト。

判定（製品固有かどうか）は行わない。列構成の集計と、使用不可の理由の列挙のみ。

Usage:
    python3 fleet_sweep_legacy.py
"""
import csv
import glob
import os
from collections import defaultdict

REPO = "/Users/kouhei/tmp/github/stampfly_ecosystem"
LOG_DIR = f"{REPO}/logs"
EDU_DIR = f"{REPO}/analysis/datasets/education"
SYSID_DIR = f"{REPO}/analysis/datasets/sysid"
VEHICLE_OLD_LOGS = f"{REPO}/firmware/vehicle_old/logs"

MOTOR_DUTY_HINTS = ("motor_1", "motor_2", "motor_3", "motor_4",
                     "duty_fr", "duty_rr", "duty_rl", "duty_fl",
                     "motor_duty", "duty_m1", "duty_m2", "duty_m3", "duty_m4")


def read_header(path):
    with open(path, "r", newline="") as f:
        first_lines = []
        for _ in range(5):
            line = f.readline()
            if not line:
                break
            first_lines.append(line.rstrip("\n"))
    # Skip comment lines (starting with '#') to find the real header
    header_line = None
    for line in first_lines:
        if line.startswith("#"):
            continue
        header_line = line
        break
    cols = header_line.split(",") if header_line else []
    return cols, first_lines


def classify(cols):
    cols_l = [c.strip().lower() for c in cols]
    has_motor_duty = any(h in cols_l for h in MOTOR_DUTY_HINTS)
    has_gyro_z = "gyro_z" in cols_l or "r" in cols_l  # r = body yaw rate (education synthetic)
    has_stick = any(c.startswith("ctrl_") for c in cols_l) or "setpoint" in cols_l
    has_voltage = any("volt" in c for c in cols_l)
    return dict(has_motor_duty=has_motor_duty, has_gyro_z=has_gyro_z,
                has_stick=has_stick, has_voltage=has_voltage, n_cols=len(cols))


def survey_dir(pattern, label):
    files = sorted(glob.glob(pattern))
    print(f"\n=== {label}: {len(files)} files ===")
    schema_groups = defaultdict(list)
    for f in files:
        cols, _ = read_header(f)
        key = tuple(cols)
        schema_groups[key].append(os.path.basename(f))
    for i, (key, members) in enumerate(schema_groups.items()):
        info = classify(list(key))
        print(f"  schema #{i}: n_files={len(members)} n_cols={info['n_cols']} "
              f"motor_duty={info['has_motor_duty']} gyro_z={info['has_gyro_z']} "
              f"stick={info['has_stick']} voltage={info['has_voltage']}")
        print(f"    example: {members[0]}")
        if len(members) <= 5:
            print(f"    files: {members}")
    return schema_groups


def main():
    print("StampFly legacy CSV schema survey")
    print("=" * 60)

    survey_dir(f"{LOG_DIR}/*.csv", "logs/*.csv (vehicle_old telemetry CSV, all families: "
                                   "hover*, hover_test_static*, log_wifi_test*, flight.csv, "
                                   "stampfly_wifi_*, stampfly_udp_*)")
    survey_dir(f"{EDU_DIR}/*.csv", "analysis/datasets/education/*.csv")
    survey_dir(f"{SYSID_DIR}/*.csv", "analysis/datasets/sysid/*.csv")
    vo = glob.glob(f"{VEHICLE_OLD_LOGS}/*.csv") + glob.glob(f"{VEHICLE_OLD_LOGS}/*.bin") + \
        glob.glob(f"{VEHICLE_OLD_LOGS}/*.jsonl")
    print(f"\n=== firmware/vehicle_old/logs/: {len(vo)} data files "
          f"(directory only contains .gitignore) ===")

    print("\n" + "=" * 60)
    print("CONCLUSION (schema-level, no duty computation performed):")
    print("- logs/*.csv (76 files, 7 header schema variants) carry only AGGREGATE")
    print("  control outputs: ctrl_throttle/ctrl_roll/ctrl_pitch/ctrl_yaw (pre-mixer,")
    print("  stick/attitude-loop level). No per-motor duty/PWM column exists in ANY")
    print("  schema variant. Confirmed against firmware/vehicle_old telemetry.hpp: none")
    print("  of TelemetryWSPacket / FFTSample / TelemetryFFTBatchPacket / ExtendedSample")
    print("  / TelemetryExtendedBatchPacket carry per-motor duty fields either -- the")
    print("  vehicle_old WiFi/UDP telemetry protocol never transmitted per-motor duty.")
    print("  => duty_diff (CCW-mean - CW-mean) CANNOT be computed from these files.")
    print("- analysis/datasets/education/hover_30s.csv and rate_step_response.csv DO")
    print("  contain motor_1..motor_4 columns, but they are SYNTHETIC data generated by")
    print("  lib/stampfly_edu/generate_samples.py (commit ab6a8f0, 'feat(education):")
    print("  implement Sprint 1'), not real hardware telemetry. motor_1..4 are produced")
    print("  by a closed-form response model, not measured PWM duty. Unusable for a")
    print("  product-specific asymmetry claim.")
    print("- analysis/datasets/sysid/motor_steady_state.csv is a 9-row bench")
    print("  single-motor voltage-vs-omega characterization table (no CW/CCW group,")
    print("  no time series, no vehicle context). Unusable.")
    print("- firmware/vehicle_old/logs/ contains no data files (only .gitignore).")


if __name__ == "__main__":
    main()
