/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Kouhei Ito
 *
 * Part of StampFly Ecosystem (SIL host bench).
 * https://github.com/M5Fly-kanazawa/stampfly_ecosystem
 */

/**
 * @file plant.hpp
 * @brief SIL physics plant — MuJoCo rigid body + self-written motor/sensor/wind.
 *        SIL 物理プラント — MuJoCo 剛体＋自作のモータ/センサ/風。
 *
 * This is the algorithm-independent SIL bench (RESET_PLAN §5 ①). It owns the
 * MuJoCo model, turns per-motor duty (from the firmware's actuator_motor topic)
 * into thrust + yaw reaction torque + wind, steps the physics, and synthesizes
 * the StampFly sensors (IMU/ToF/baro/flow/mag) in body-FRD via the frames module.
 *
 * これはアルゴリズム非依存の SIL ベンチ（RESET_PLAN §5 ①）。MuJoCo モデルを所有し、
 * 各モータ duty（ファームの actuator_motor トピック由来）を推力＋ヨー反トルク＋風に
 * 変換して物理を進め、StampFly センサ（IMU/ToF/baro/flow/mag）を frames 経由で
 * 機体 FRD に合成する。
 *
 * Design philosophy (RESET_PLAN §6): the motor/sensor models are SELF-WRITTEN;
 * MuJoCo's built-in <accelerometer>/<gyro> are used as the synthesis basis and as
 * a trusted answer-check. Coordinate transforms happen ONLY in frames.hpp.
 *
 * 設計方針（RESET_PLAN §6）: モータ/センサモデルは自作。MuJoCo 内蔵の
 * <accelerometer>/<gyro> を合成の土台かつ信頼できる答え合わせに使う。座標変換は
 * frames.hpp の中だけで行う。
 *
 * @design simulator/sil/docs/coordinate_frames.md §4.1-4.5                 [OK]
 * @design simulator/sil/RESET_PLAN.md §5-6 — algorithm-independent bench   [--]
 */

#pragma once

#include <cstdint>
#include <cmath>
#include <vector>

#include <mujoco/mujoco.h>

#include "sf_math.hpp"
#include "frames.hpp"
#include "data_types.hpp"
#include "sensor_noise.hpp"
#include "generated_params.hpp"

namespace sil {

/// SIL physics plant: MuJoCo + self-written motor/sensor/wind models.
/// SIL 物理プラント: MuJoCo ＋自作のモータ/センサ/風モデル。
class Plant {
public:
    /// Tunable plant parameters (StampFly physical values + plant-only models).
    ///
    /// Motor + propeller model: the electromechanical ODE ported from
    /// simulator/genesis/motor_model.py (Model Fidelity backlog #2, 2026-07-26):
    ///   dω/dt = [-(Dm + Km²/Rm)·ω - Cq·ω² - Qf + Km·V/Rm] / Jmp,   V = duty·v_batt
    /// integrated by classical RK4 every substep — NOT a fitted k·duty² and NOT the
    /// prior static V=Am·ω²+Bm·ω+Cm curve (retired together with solveOmega()). The
    /// per-motor command is a normalized duty in [0,1] (the firmware mixer's output).
    /// Thrust T = η·Ct·ω² (η = thrust_efficiency); per-motor aerodynamic reaction
    /// torque Q = Cq·ω² (used directly in substep(), not via the old kappa·T
    /// shortcut — see substep()'s yaw-torque comment in plant.cpp).
    ///
    /// モータ＋プロペラモデル: simulator/genesis/motor_model.py から移植した電気機械
    /// ODE（Model Fidelity バックログ#2, 2026-07-26）:
    ///   dω/dt = [-(Dm+Km²/Rm)·ω - Cq·ω² - Qf + Km·V/Rm]/Jmp,   V = duty·v_batt
    /// を substep 毎に古典 RK4 で積分（フィットの k·duty² でも、旧静的曲線
    /// V=Am·ω²+Bm·ω+Cm でもない — solveOmega() と共に撤去済み）。各モータ指令は正規化
    /// duty[0,1]（ファームのミキサー出力）。推力 T=η·Ct·ω²（η=thrust_efficiency）、
    /// モータ毎の空力反トルク Q=Cq·ω²（substep() で直接使用、旧 kappa·T 近似は廃止 —
    /// plant.cpp の substep() ヨートルクコメント参照）。
    struct Config {
        float v_batt   = 3.7f;      ///< 1S LiPo nominal terminal voltage [V]

        // Motor/propeller electromechanical ODE coefficients — all five sourced from
        // generated_params.hpp (sil_params::adopted::*), generated by `sf params
        // generate` from control/models/stampfly_physical.yaml
        // calibration_sets.measured_2026_07 (the single measurement campaign,
        // 2026-07-15/16/26, that identified them together — see that YAML's notes
        // for method/date per coefficient).
        // モータ/プロペラ電気機械 ODE 係数 — 5つ全て generated_params.hpp
        // （sil_params::adopted::*）由来。`sf params generate` が
        // control/models/stampfly_physical.yaml の calibration_sets.measured_2026_07
        // （2026-07-15/16/26 の単一測定キャンペーンで連動同定）から生成
        // （係数毎の方法・日付は同 YAML の note 参照）。
        float Ct  = sil_params::adopted::CT;   ///< thrust coeff [N/(rad/s)²]  (T = Ct·ω²)
        float Cq  = sil_params::adopted::CQ;   ///< torque coeff [N·m/(rad/s)²]  (Q = Cq·ω², also the ODE's aero-drag term)
        float Jmp = sil_params::adopted::JMP;  ///< rotor inertia [kg·m²]
        float Dm  = sil_params::adopted::DM;   ///< viscous damping [N·m·s/rad] — 0 (2026-07-26 coast-down 3-term refit: b term not detectable, lower-bound clamped)
        float Qf  = sil_params::adopted::QF;   ///< Coulomb friction torque [N·m] (2026-07-26 coast-down 3-term refit, c term × Jmp)

        /// Real-world thrust efficiency vs the ODE's idealized T=Ct·ω² curve (motor/prop
        /// losses + battery sag the firmware's vbat reading doesn't capture). DEFAULT 1.0
        /// as of 2026-07-26 (backlog #2): the prior 1/1.12 ("worn motor" fudge) compensated
        /// for the LEGACY Ct (1.00e-8, ≈1.49× too large vs the measured 6.7e-9 now wired in
        /// directly above) — with the real Ct in place, that compensating fudge is no longer
        /// physically warranted. The parameter itself is KEPT (not deleted) for future
        /// flight-log recalibration (Model Identity); override per-run with
        /// SIL_EMU_THRUST_EFF (emu_main.cpp) for A/B testing.
        /// 実機の推力効率（ODE理想曲線 T=Ct·ω² 比、モータ/プロップ損失＋ファームが測れない
        /// 電池サグ）。2026-07-26（バックログ#2）既定 1.0 に変更: 旧 1/1.12（「摩耗モータ」
        /// ファッジ係数）は旧 Ct(1.00e-8、上で直接配線した実測6.7e-9の約1.49倍過大)を
        /// 打ち消すためのものだった — 実測 Ct を配線した今、その補正は物理的にもう不要。
        /// パラメータ自体は削除せず残す（将来のフライトログ再較正=Model Identity 用）。
        /// SIL_EMU_THRUST_EFF（emu_main.cpp）で実行毎に上書き可（A/B比較用）。
        float thrust_efficiency = 1.0f;  ///< 1.0 = ODE curve is the actual output (see above)

        // --- Motor path transport delay (dead time) — Model fidelity ---
        // The identified plant model G(s) = b·e^(−Ls)/(s(Ts+1)) (docs/architecture/
        // simulation-policy.md §2 layer 1) factors the duty→rate response into a pure
        // transport delay L in series with a first-order lag T. Real-hardware system ID
        // (`sf sysid rate-fit`) measured L = 14.7 ms (roll) / 8.4 ms (pitch) / 11.0 ms
        // (yaw) (simulation-policy.md backlog #1). As of 2026-07-26 (backlog #2) this
        // Plant's lag source is the motor+propeller ODE's own electromechanical time
        // constant (τ_eff ≈ 16.3 ms at hover, see Config's ODE comment above) rather
        // than a separate first-order duty-smoothing stage (the retired motor_tau) —
        // there is STILL no explicit dead time, so this knob remains meaningful. This
        // models L as a pure delay inserted BEFORE the ODE integration in the
        // duty→thrust path (substep()), NOT after: battery current, ground effect and
        // yaw reaction torque all consume the SAME substep's thrust, so delaying
        // thrust itself (rather than the duty command feeding the ODE) would break
        // that same-substep consistency.
        // DEFAULT 0 (OFF) so the clean path stays byte-identical and existing scenarios
        // (tuned without this delay) are unaffected — enable per-scenario via
        // SIL_EMU_MOTOR_DELAY (sf sil scenario --motor-delay), the same opt-in pattern
        // as ge_gain/turbulence_n above.
        //
        // モータ経路の輸送遅れ（むだ時間）。同定モデル G(s)=b·e^(−Ls)/(s(Ts+1))
        // （simulation-policy.md §2 層1）は duty→レート応答を「純遅延 L」と「一次遅れ T」の
        // 直列に分解する。実機同定（sf sysid rate-fit）は L=14.7ms(roll)/8.4ms(pitch)/
        // 11.0ms(yaw)（simulation-policy.md バックログ#1）。2026-07-26（バックログ#2）
        // 時点で本 Plant の遅れ源はモータ+プロペラ ODE 自身の電気機械時定数
        // （ホバ点で τ_eff≈16.3ms、上の Config の ODE コメント参照）であり、別建ての
        // 一次遅れ段（撤去済みの motor_tau）ではない — それでも明示的なむだ時間は無い
        // ままなので、本ノブは引き続き意味を持つ。duty→推力経路（substep()）で ODE 積分の
        // **手前**に純遅延として挿入する（**後段の推力は不可** — 電池電流・地面効果・
        // ヨー反トルクは同じ substep の推力を使うため、推力自体を遅らせると整合が崩れる）。
        // 既定 0（OFF）でクリーン経路はバイト一致、既存シナリオ（遅延無しで調整済み）へ
        // 影響しない — SIL_EMU_MOTOR_DELAY（sf sil scenario --motor-delay）でシナリオ毎に
        // 有効化（上の ge_gain/turbulence_n と同じオプトイン方式）。
        float motor_delay_ms = 0.0f;  ///< duty-path transport delay [ms] (0 = OFF/bypass)

        // --- Ground effect — Model fidelity ---
        // Extra rotor lift near the floor: each motor's thrust is scaled by
        //   1 + ge_gain·exp(−z / ge_height),  z = body height above the floor [m].
        // Negligible a few ge_height up (≈0 at flight altitude), strong in the last few
        // cm. This is the physics behind the touchdown "float" the pilot reports — near
        // the ground the craft holds altitude on REDUCED thrust, so a constant-velocity
        // descent stalls and a ToF-only landing detector (needs <5cm) never triggers. The
        // armed touchdown detector (TakeoffLandingMgr) keys off exactly this: near-ground +
        // descent-stalled + thrust-below-hover. 0 disables it (byte-identical to pre-GE).
        // 地面効果: 接地近傍の余剰ローター揚力。各モータ推力を 1 + ge_gain·exp(−z/ge_height)
        // 倍する（z=床上の機体高さ[m]）。数 ge_height 以上で無視でき（飛行高度で≈0）、最後の
        // 数 cm で強く効く。これがパイロット報告の着陸「フロート」の物理 — 接地近傍で機体は
        // 低推力で高度を保つため、一定速度降下が停滞し、ToF のみ（<5cm 必須）の着陸検出器が
        // 発火しない。armed 接地検出器はまさにこれ（接地近傍＋降下停滞＋推力ホバー以下）を
        // 起点にする。0 で無効（GE 導入前とバイト一致）。
        // DEFAULT OFF (0) so the clean path stays byte-identical and the existing scenarios
        // (tuned without GE) are unaffected — enable per-scenario via SIL_EMU_GROUND_EFFECT
        // (sf sil scenario --ground-effect), exactly like the sensor-noise knob. GE is real
        // physics but, like noise, it is opt-in for determinism; the firmware touchdown
        // detector is always active, so on HARDWARE (GE always present) it works regardless.
        // 既定 OFF(0): クリーン経路をバイト一致に保ち、GE 無しで調整済みの既存シナリオを乱さない —
        // SIL_EMU_GROUND_EFFECT（sf sil scenario --ground-effect）でシナリオ毎に有効化（ノイズノブ
        // と同様）。GE は実在物理だがノイズ同様に決定論のためオプトイン。ファーム接地検出器は常時有効ゆえ
        // 実機（GE 常在）では常に効く。
        float ge_gain   = 0.0f;     ///< extra lift fraction as z→0 (0 = OFF) / z→0 での余剰揚力率（0=OFF）
        float ge_height = 0.045f;   ///< [m] ground-effect e-folding height / 減衰高さ

        // --- Battery (1S LiPo) sag/discharge model — Model fidelity ---
        // When enabled, the supply voltage is DYNAMIC: v_batt(t) = OCV(SoC) − I·R_int,
        // with the battery current I summed from each motor's electrical draw
        // I_i = (V_motor,i − Km·ω_i)/Rm (motor electrical model, params doc §3) plus a
        // quiescent avionics draw. SoC is depleted by Coulomb counting. DISABLED by
        // default → constant v_batt (the physics/smoke tests probe the motor curve at a
        // fixed nominal voltage). The closed-loop emulator (emu_vehicle) enables it
        // so the firmware's live-voltage thrust→duty compensation has a real sag to track.
        // 電池(1S LiPo)サグ/放電モデル。有効時は電源電圧が動的: v_batt=OCV(SoC)−I·R_int。
        // 電池電流 I は各モータ電気電流 I_i=(V_motor,i−Km·ω_i)/Rm（params文書§3）＋アビオ静止
        // 電流の総和。SoC はクーロンカウントで減少。既定 OFF（物理/smoke テストは固定公称で
        // モータ曲線を検証）。閉ループ emu が有効化し、ファームの実電圧 thrust→duty 補償に
        // 追従すべき実サグを与える。
        bool  batt_model_enable  = false;
        float batt_capacity_mah  = 300.0f;   ///< 1S LiPo capacity [mAh] (juida2026 EVIDENCE)
        float batt_r_int         = 0.1f;     ///< battery internal resistance [Ω] (vpython model)
        float batt_full_v        = 4.2f;     ///< OCV at full charge [V]
        float batt_empty_v       = 3.3f;     ///< OCV at empty [V]
        float batt_initial_frac  = 1.0f;     ///< initial state of charge [0..1] (1 = full)
        // motor_Rm/motor_Km now feed BOTH the ODE dynamics above (dω/dt uses Km²/Rm
        // and Km·V/Rm directly, Config's ODE comment) AND the battery-current
        // estimate below (i_motor = (V−Km·ω)/Rm, plant.cpp updateBattery caller,
        // used only when batt_model_enable=true). Both are legitimate direct uses —
        // Rm/Km are genuine electrical parameters of the same physical motor, not
        // artifacts of the retired Am/Bm/Cm curve (that curve was an empirically-fit
        // V-ω relation that used to stand in for the true electromechanical dynamics;
        // solveOmega(), which never referenced Rm/Km, is gone as of 2026-07-26
        // backlog #2). Phase 1 (2026-07-26): both source from generated_params.hpp
        // (sil_params::adopted::RM/KM), generated by `sf params generate` from
        // control/models/stampfly_physical.yaml.
        // motor_Rm/motor_Km は上の ODE 動特性（dω/dt に Km²/Rm と Km·V/Rm を直接使用、
        // Config の ODE コメント参照）と下のバッテリー電流推定（i_motor=(V−Km·ω)/Rm、
        // batt_model_enable=true の時のみ）の両方で使用。どちらも正当な直接使用——
        // Rm/Km は同一実モータの電気パラメータであり、廃止した Am/Bm/Cm 曲線
        // （真の電気機械動特性の代わりを務めていた実験フィットの V-ω 関係）の副産物では
        // ない（Rm/Km を一切参照しなかった solveOmega() は 2026-07-26 バックログ#2で
        // 撤去済み）。Phase 1（2026-07-26）: 両方 generated_params.hpp
        // （sil_params::adopted::RM/KM）由来、`sf params generate` が
        // control/models/stampfly_physical.yaml から生成。
        float motor_Rm           = sil_params::adopted::RM;   ///< winding resistance [Ω] (paper LCR measurement, 2026-07-15, teacher decision commit 9a656a9f; was 0.34 legacy/possibly-different-unit LCR)
        float motor_Km           = sil_params::adopted::KM; ///< back-EMF constant [V/(rad/s)] (direct measurement, 2026-07-16, tools/sysid/defaults.py; was 6.12e-4 = stale reference calc from legacy Cq(9.71e-11)·Rm(0.34)/Am)
        float avionics_current_a = 0.1f;     ///< MCU + sensors quiescent draw [A]
        // Phase 1 (2026-07-26): sourced from generated_params.hpp (sil_params::MASS),
        // generated by `sf params generate` from control/models/stampfly_physical.yaml
        // (constants.mass) -- bit-identical to the prior hand-written literal 0.037f.
        // Phase 1（2026-07-26）: generated_params.hpp（sil_params::MASS）由来。
        // `sf params generate` が control/models/stampfly_physical.yaml（constants.mass）
        // から生成——従来の手書きリテラル 0.037f とビット一致。
        float mass     = sil_params::MASS;    ///< body mass [kg]
        float g        = 9.81f;     ///< gravity [m/s²]
        float health[4] = {1.0f, 1.0f, 1.0f, 1.0f}; ///< per-motor thrust gain (1=healthy)
        sf::math::Vec3 wind_force_ned = {0.0f, 0.0f, 0.0f}; ///< external wind force NED [N]
        // Deterministic band-limited TURBULENCE (horizontal NED force, 1–3 Hz sinusoid sum)
        // to excite the attitude-wobble band for the wobble-minimization study. Repeatable
        // (no RNG), 0 = off. Added on top of wind_force_ned each substep. See plant.cpp.
        // 決定論的な帯域制限乱流（水平NED力, 1–3Hz正弦和）。姿勢ふらつき帯域を励起して
        // ふらつき最小化研究の外乱とする。再現可能（RNG不使用）、0=off。
        float turbulence_n = 0.0f;  ///< turbulence force amplitude [N] (0 = off)
        /// Deterministic RAW IMU bias (body FRD), modeling the pre-calibration MEMS
        /// offset. Added as a constant to the synthetic IMU output. Default zero. The
        /// firmware boot calibration measures and removes it (P2-3 contrast test).
        /// 決定論的な生 IMU バイアス（機体 FRD）。校正前の MEMS オフセットを模擬。合成 IMU
        /// 出力に定数として加算。既定ゼロ。ファームの起動校正が測定・除去する（P2-3 対照試験）。
        sf::math::Vec3 imu_bias_accel = {0.0f, 0.0f, 0.0f}; ///< accel raw bias [m/s²]
        sf::math::Vec3 imu_bias_gyro  = {0.0f, 0.0f, 0.0f}; ///< gyro  raw bias [rad/s]
        float flow_rad_per_pixel = 0.00222f; ///< PMW3901 rad per count (matches ESKF)
        SensorNoise::Config noise; ///< IMU sensor noise (N0, default OFF). RESET_PLAN §13
    };

    /// Ground-truth state in StampFly conventions (NED world, FRD body).
    /// StampFly 規約での真値状態（NED 世界・FRD 機体）。
    struct Truth {
        sf::math::Vec3 pos_ned;    ///< position NED [m]
        sf::math::Vec3 vel_ned;    ///< velocity NED [m/s]
        sf::math::Vec3 omega_frd;  ///< body angular rate FRD [rad/s]
        sf::math::Quat q_nb;       ///< attitude body→NED
    };

    Plant() = default;
    ~Plant();
    Plant(const Plant&) = delete;
    Plant& operator=(const Plant&) = delete;

    /// Load the MJCF model and cache sensor/body ids. Returns false on failure.
    /// MJCF モデルを読み、センサ/ボディ id をキャッシュ。失敗時 false。
    bool init(const char* model_path, const Config& cfg);

    /// Convenience overload using the default Config. / 既定 Config を使う簡易版。
    bool init(const char* model_path) { return init(model_path, Config{}); }

    /// Set the commanded per-motor duty target (index 0..3 = M1FR/M2RR/M3RL/M4FL,
    /// matching MotorOutput.duty and the MJCF rotor order, 1:1, no reshuffle).
    /// 指令の各モータ duty 目標を設定（添字 0..3 = M1FR/M2RR/M3RL/M4FL、MotorOutput.duty
    /// と MJCF ロータ順に 1:1 対応、並べ替えなし）。
    void setDuty(const sf::MotorOutput& cmd);

    /// Snap actual motor speed to the commanded target (skip spool-up lag). Used to
    /// warm-start a test at hover so the first-order lag does not cause an initial dip.
    /// 実モータ回転を指令目標に即時一致させる（スプールアップ遅れを飛ばす）。ホバーから
    /// テストを暖機起動し、一次遅れによる初期沈下を避けるために使う。
    void primeMotors();

    /// Set the external wind force in NED [N] (default zero).
    /// NED の外乱風力 [N] を設定（既定ゼロ）。
    void setWind(const sf::math::Vec3& force_ned);

    /// Set per-motor thrust health gain at runtime (1=healthy, 0=dead). Used by the
    /// P7 disturbance scenarios to degrade a motor mid-flight and watch the mixer
    /// compensate. Out-of-range motor index is ignored; gain is clamped to [0,1].
    /// 各モータの推力健全度ゲインを実行時設定（1=正常, 0=停止）。P7 外乱シナリオが飛行中に
    /// モータを劣化させ、ミキサーの補償を見るのに使う。範囲外 index は無視、gain は [0,1] にクランプ。
    void setHealth(int motor, float gain);

    /// Set the deterministic raw IMU bias (body FRD) at runtime — a constant added to
    /// the synthetic accel [m/s²] / gyro [rad/s]. Models a pre-calibration MEMS offset
    /// so the firmware boot calibration has something real to measure and remove.
    /// 決定論的な生 IMU バイアス（機体 FRD）を実行時設定 — 合成 accel[m/s²]/gyro[rad/s] に
    /// 定数加算。校正前 MEMS オフセットを模擬し、ファーム起動校正に測定・除去対象を与える。
    void setImuBias(const sf::math::Vec3& accel_bias, const sf::math::Vec3& gyro_bias);

    /// Place the body at rest, level, at height z [m] (MuJoCo ENU up). Used to
    /// start a flight on the ground (z ≈ box half-height) for a takeoff demo.
    /// 機体を高さ z [m]（MuJoCo ENU 上）で水平・静止配置する。地上から離陸する
    /// デモのため、地上スタート（z ≈ 箱の半分の高さ）に使う。
    void setStartHeight(float z);

    /// Begin a PHYSICAL HANDLING maneuver: a hand lifts the (crashed) craft, rights it
    /// to level, carries it to a placement spot and sets it back down on the ground —
    /// the SIL stand-in for "pick the drone up and put it back" of the re-fly workflow.
    /// While it runs the Plant PRESCRIBES a smooth kinematic trajectory (NO dynamics, NO
    /// teleport): the body pose moves continuously through three smootherstep phases —
    ///   lift  (rise straight up from the crash pose to carry_alt, start righting),
    ///   carry (translate to place_x/place_y at carry_alt, finish righting to level),
    ///   place (lower straight down onto the ground at place_x/place_y, stay level).
    /// The synthetic IMU specific force is computed ANALYTICALLY from the trajectory's
    /// acceleration (frames::accel_body_frd) and the gyro from its angular velocity, so
    /// the firmware sees a physically consistent lift/right/carry/place — the ToF rises
    /// above the airborne threshold (→ IDLE_HELD) and drops back on placement (→
    /// IDLE_GROUND → re-calibration). Smootherstep gives zero velocity AND acceleration
    /// at every phase boundary (C²), so the path — and the IMU — has no discontinuity.
    /// place_x/place_y are NED [m]; carry_alt is height [m] up; the three durations [s]
    /// each must be > 0. Capturing the start pose from truth() means an inverted/tilted
    /// crash is righted by the same SLERP-to-level.
    ///
    /// 物理ハンドリング動作を開始: 手が（墜落した）機体を持上げ→正立へ起こし→設置点へ運搬→
    /// 地面に戻す ― 再飛行ワークフローの「ドローンを拾って置き直す」の SIL 代理。実行中は Plant が
    /// 滑らかなキネマティック軌道を規定する（動力学なし・teleport なし）: 機体姿勢が3つの
    /// smootherstep 相を連続に動く ― lift（墜落姿勢から carry_alt まで真上に上げ、起こし開始）、
    /// carry（carry_alt で place_x/place_y へ並進、水平へ起こし完了）、place（place_x/place_y で
    /// 真下に地面へ降ろし、水平維持）。合成 IMU 比力は軌道の加速度から解析的に（frames::
    /// accel_body_frd）、ジャイロは角速度から計算するので、ファームは物理的に整合した
    /// 持上げ/正立/運搬/設置を見る ― ToF が空中閾値を超え（→IDLE_HELD）、設置で戻る（→IDLE_GROUND
    /// →再校正）。smootherstep は各相境界で速度と加速度が共にゼロ（C²）ゆえ軌道（と IMU）に
    /// 不連続が無い。place_x/place_y は NED[m]、carry_alt は高さ[m]、3つの所要時間[s]は各 >0。
    /// 開始姿勢を truth() から捕える＝反転/傾いた墜落も同じ「水平への SLERP」で起こされる。
    void startHandling(float carry_alt_m, float place_x_ned, float place_y_ned,
                       float lift_s, float carry_s, float place_s);

    /// True while a handling maneuver is in progress (the kinematic override is active
    /// and the synthetic IMU is the analytic handling value, not the MuJoCo dynamics).
    /// ハンドリング動作の実行中に true（キネマティック上書きが有効で、合成 IMU は MuJoCo
    /// 動力学でなく解析ハンドリング値）。
    bool handlingActive() const { return handling_active_; }

    /// Per-motor duty [0,1] that produces hover thrust (mg/4) at ODE STEADY STATE
    /// (backlog #2, 2026-07-26). Inverts the model: T = mg/4 → ω = √(T/(η·Ct)) →
    /// V = Km·ω + (Rm/Km)·(Cq·ω²+Dm·ω+Qf) → duty = V/v_batt. See plant.cpp for the
    /// equilibrium derivation (same equation as dutyToThrust(), solved the other way).
    /// ODE 定常状態でホバー推力（mg/4）を出す各モータ duty[0,1]（バックログ#2,
    /// 2026-07-26）。モデルを逆算: T=mg/4 → ω=√(T/(η·Ct)) →
    /// V=Km·ω+(Rm/Km)·(Cq·ω²+Dm·ω+Qf) → duty=V/v_batt。平衡式の導出は plant.cpp
    /// 参照（dutyToThrust() と同じ式を逆方向に解く）。
    float hoverDuty() const;

    /// Convert a single motor duty [0,1] to STEADY-STATE thrust [N] via the ODE's
    /// equilibrium (backlog #2, 2026-07-26) — the eventual thrust a held duty
    /// settles to, not the per-step transient (that is substep()'s RK4 integration).
    /// 1モータの duty[0,1] を ODE 平衡での定常推力[N] に変換する（バックログ#2,
    /// 2026-07-26）— 保持した duty が最終的に落ち着く推力（過渡は substep() の
    /// RK4 積分が担う）。
    float dutyToThrust(float duty) const;

    /// Battery terminal voltage [V] as the INA3221 power monitor would measure it.
    /// With the battery model OFF this is the fixed nominal (cfg_.v_batt); with it
    /// ON it is the dynamic terminal voltage OCV(SoC) − I·R_int updated each substep.
    /// The motor curve (duty→thrust) and the firmware (thrust→duty) both use this
    /// value, so the closed loop stays consistent (Model Identity).
    /// INA3221 電源モニタが測る電池端子電圧 [V]。電池モデル OFF なら固定公称（cfg_.v_batt）、
    /// ON なら substep ごとに更新される動的端子電圧 OCV(SoC)−I·R_int。モータ曲線(duty→推力)
    /// とファーム(推力→duty)が同じ値を使うので閉ループが整合（Model Identity）。
    float batteryVoltage() const { return v_batt_; }

    /// Advance the physics by dt of VIRTUAL time, integrating in fixed
    /// model-timestep (m_->opt.timestep) substeps with a carried remainder, so
    /// the physics clock tracks the caller's virtual clock 1:1. mj_step always
    /// advances exactly one model timestep (it takes no dt), and the controller
    /// samples at 400 Hz while the plant integrates at the finer model timestep
    /// (≥10× oversampling) — the inter-sample plant dynamics are preserved.
    /// 物理を「仮想時間 dt」ぶん進める。固定モデル timestep（m_->opt.timestep）刻みの
    /// substep で積分し端数を繰り越す → 物理時計が呼び出し側の仮想時計と 1:1 で一致。
    /// mj_step は常にモデル timestep を1回進める（dt を取らない）。制御は 400Hz で
    /// サンプルし、プラントはより細かいモデル timestep（10倍以上）で積分する。
    void step(float dt);

    /// Ground-truth state (NED/FRD), converted from MuJoCo via frames only.
    /// 真値状態（NED/FRD）。MuJoCo から frames だけで変換。
    Truth truth() const;

    // Synthetic sensors (body-FRD, driver-normalized convention). 合成センサ。
    sf::ImuData  imu()  const;  ///< accel [m/s²] (−9.8 at rest) + gyro [rad/s], FRD
    sf::TofData  tof()  const;  ///< downward distance [m]
    sf::BaroData baro() const;  ///< pressure-altitude [m] (= −pos_z)
    sf::FlowData flow() const;  ///< PMW3901 dx/dy [counts] over the last step
    sf::MagData  mag()  const;  ///< body magnetic field [µT] (default ref, OFF by default)

    const mjModel* model() const { return m_; }  ///< for the optional viewer / ビューア用
    mjData*        data()        { return d_; }   ///< for the optional viewer / ビューア用

private:
    /// Ground-effect lift multiplier at body height z [m] (ENU): 1 + ge_gain·exp(−z/ge_height).
    /// 1 (no effect) when ge_gain ≤ 0 or far from the floor. See Config::ge_gain.
    /// 機体高さ z[m] での地面効果揚力倍率。ge_gain≤0 / 床から遠いと 1。Config::ge_gain 参照。
    float groundEffectMultiplier(float z_body_m) const {
        if (cfg_.ge_gain <= 0.0f) return 1.0f;
        return 1.0f + cfg_.ge_gain * std::exp(-z_body_m / cfg_.ge_height);
    }

    /// One fixed-timestep physics substep of length h [s]: motor ODE (RK4) → thrust →
    /// reaction torque + wind → mj_step → advance noise. h is the model timestep.
    /// 長さ h [s] の固定刻み物理 substep 1回: モータ ODE(RK4) → 推力 → 反トルク＋風 →
    /// mj_step → ノイズ前進。h はモデル timestep。
    void substep(float h);

    /// One fixed-timestep step of the PRESCRIBED handling trajectory (length h [s]):
    /// advance the handling clock, evaluate the smootherstep pose/velocity/acceleration,
    /// write qpos/qvel into MuJoCo, mj_forward to refresh the position sensors, and store
    /// the analytic IMU specific force + gyro. Replaces substep() while handling is active
    /// (no dynamics integration). 規定ハンドリング軌道の固定刻み 1 ステップ（長さ h[s]）:
    /// ハンドリング時計を進め、smootherstep の姿勢/速度/加速度を評価し、qpos/qvel を MuJoCo に
    /// 書込み、mj_forward で位置センサを更新、解析 IMU 比力＋ジャイロを保存。ハンドリング中は
    /// substep() を置き換える（動力学積分なし）。
    void handlingSubstep(float h);

    /// Motor+propeller ODE right-hand side dω/dt (backlog #2, 2026-07-26) — the RK4
    /// integrand substep() calls every substep. See plant.cpp for the derivation.
    /// モータ+プロペラ ODE の右辺 dω/dt（バックログ#2, 2026-07-26）— substep() が
    /// 毎回呼ぶ RK4 の被積分関数。導出は plant.cpp 参照。
    float omegaDot(float omega, float v_motor) const;

    /// Steady-state prop speed ω for a HELD voltage V (positive root of the ODE's
    /// equilibrium dω/dt = 0). Used ONLY by dutyToThrust() and primeMotors() (warm
    /// start) — NOT part of substep()'s per-step dynamics, which integrates the ODE
    /// directly rather than solving for an instantaneous equilibrium.
    /// 保持電圧 V に対する定常回転 ω（ODE 平衡 dω/dt=0 の正根）。dutyToThrust() と
    /// primeMotors()（暖機起動）のみで使用 — substep() の毎ステップ動特性では
    /// 使わない（そちらは瞬時平衡を解くのでなく ODE を直接積分する）。
    float steadyStateOmega(float v_motor) const;

    /// Open-circuit voltage [V] from remaining charge [mAh] (1S LiPo discharge
    /// curve, ported from simulator/vpython/sensors/power_monitor.py).
    /// 残容量 [mAh] → 開回路電圧 [V]（1S LiPo 放電曲線、vpython 実装から移植）。
    float ocvFromCharge(float charge_mah) const;

    /// Update the battery: Coulomb-count the charge and recompute the terminal
    /// voltage v_batt_ = OCV(SoC) − I·R_int. No-op when the model is disabled.
    /// 電池更新: クーロンカウントで容量を減らし端子電圧 v_batt_=OCV(SoC)−I·R_int を再計算。
    /// モデル無効時は何もしない。
    void updateBattery(float i_total_a, float h);

    /// Pointer to a named sensor's data inside d_->sensordata.
    /// 名前付きセンサの d_->sensordata 内の先頭ポインタ。
    const double* sensor(int sid) const { return d_->sensordata + m_->sensor_adr[sid]; }

    mjModel* m_ = nullptr;
    mjData*  d_ = nullptr;
    Config cfg_;
    SensorNoise noise_;  ///< IMU noise model (seeded; advanced each step). §13 P5

    float motor_omega_[4]  = {0.0f, 0.0f, 0.0f, 0.0f}; ///< ODE angular velocity state [rad/s] (backlog #2, 2026-07-26)
    float motor_target_[4] = {0.0f, 0.0f, 0.0f, 0.0f}; ///< commanded target duty

    // Motor transport-delay ring buffer (one per motor). Sized to delay_n_ substeps
    // in init(); empty (size 0) when the delay is OFF, in which case substep() takes
    // the explicit bypass branch and never touches these. delay_head_ is the shared
    // next write/read index (all 4 buffers advance in lock-step, one substep apart).
    // モータ輸送遅れ用リングバッファ（モータ毎）。init() で delay_n_ substep 分に確保、
    // 遅延 OFF なら空（size 0）＝ substep() は明示バイパス分岐を通り一切触れない。
    // delay_head_ は共有の次書込/読出インデックス（4バッファは同期して進む）。
    std::vector<float> delay_buf_[4]; ///< past commanded duty targets, per motor
    int delay_head_ = 0;              ///< next write/read index into delay_buf_
    int delay_n_    = 0;              ///< delay length in substeps (0 = OFF/bypass)

    float last_dt_ = 0.0025f;  ///< last step dt (for flow count integration)
    float turb_t_  = 0.0f;     ///< accumulated time for the deterministic turbulence force [s]
    double step_accum_ = 0.0;  ///< virtual-time accumulator [s] for fixed substeps

    float v_batt_ = 3.7f;          ///< current supply (terminal) voltage [V]
    float batt_charge_mah_ = 0.0f; ///< remaining battery charge [mAh] (model on)

    // --- Physical handling maneuver (kinematic override) state ---
    // 物理ハンドリング動作（キネマティック上書き）の状態。
    bool  handling_active_ = false;     ///< kinematic override in progress
    float ground_rest_z_enu_ = 0.013f;  ///< body rest height [m] ENU (set by setStartHeight)
    float handle_t_ = 0.0f;             ///< elapsed handling time [s]
    float handle_lift_s_  = 0.0f;       ///< lift  phase duration [s]
    float handle_carry_s_ = 0.0f;       ///< carry phase duration [s]
    float handle_place_s_ = 0.0f;       ///< place phase duration [s]
    sf::math::Vec3 handle_p0_ned_{};    ///< captured crash position NED [m]
    float handle_carry_z_ned_ = 0.0f;   ///< carry altitude as NED z [m] (= −carry_alt)
    float handle_place_x_ned_ = 0.0f;   ///< placement target x NED [m]
    float handle_place_y_ned_ = 0.0f;   ///< placement target y NED [m]
    float handle_ground_z_ned_ = 0.0f;  ///< ground placement NED z [m] (= −ground_rest)
    sf::math::Quat  handle_q0_nb_{};     ///< captured crash attitude (body→NED)
    sf::math::Vec3  handle_rv_flip_frd_{};  ///< right-to-level rot-vec (FRD, θ·n̂)
    sf::math::Vec3  handle_accel_frd_{0.0f, 0.0f, -9.81f};  ///< analytic specific force FRD
    sf::math::Vec3  handle_gyro_frd_{};  ///< analytic body angular rate FRD

    int body_id_  = -1;
    int accel_sid_ = -1, gyro_sid_ = -1, quat_sid_ = -1, pos_sid_ = -1, vel_sid_ = -1;
};

}  // namespace sil
